services:
  dynamodbLocal:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/shell/ || exit 0"]
      interval: 1s
      timeout: 10s
      retries: 3 
  server:
    image: omamori-finder-dev
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/code/src
      - ./requirements.txt:/code/requirements.txt
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    depends_on:
      dynamodbLocal:
        condition: service_healthy
        restart: true
    restart: always