services:
  server:
    image: omamori-finder-dev
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/code/src
  localDb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000